export const dom = {
  headerSubtitle: document.getElementById('headerSubtitle'),
  installBtn: document.getElementById('installBtn'),
  hardcodedProgramSheet: document.getElementById('hardcodedProgramSheet'),
  screens: {
    programs: document.getElementById('screen-programs'),
    session: document.getElementById('screen-session'),
    history: document.getElementById('screen-history'),
    'track-weight': document.getElementById('screen-track-weight')
  },
  tabButtons: Array.from(document.querySelectorAll('.tabbar .tab')),
  sessionDaySelect: document.getElementById('sessionDaySelect'),
  sessionRunCard: document.getElementById('sessionRunCard'),
  completeSessionBtn: document.getElementById('completeSessionBtn'),
  sessionStatus: document.getElementById('sessionStatus'),
  sessionControls: document.getElementById('sessionControls'),
  currentExerciseEl: document.getElementById('currentExercise'),
  setProgressEl: document.getElementById('setProgress'),
  prevExerciseBtn: document.getElementById('prevExerciseBtn'),
  nextExerciseBtn: document.getElementById('nextExerciseBtn'),
  setsGrid: document.getElementById('setsGrid'),
  addSetBtn: document.getElementById('addSetBtn'),
  removeSetBtn: document.getElementById('removeSetBtn'),
  sessionPreviewDay: document.getElementById('sessionPreviewDay'),
  sessionPreviewProgram: document.getElementById('sessionPreviewProgram'),
  sessionPreviewExerciseCount: document.getElementById('sessionPreviewExerciseCount'),
  sessionPreviewExercises: document.getElementById('sessionPreviewExercises'),
  sessionStartBtn: document.getElementById('sessionStartBtn'),
  historyList: document.getElementById('historyList'),
  clearHistoryBtn: document.getElementById('clearHistoryBtn'),
  historyExerciseSelect: document.getElementById('historyExerciseSelect'),
  historyChart: document.getElementById('historyChart'),
  historyChartEmpty: document.getElementById('historyChartEmpty'),
  exportBtn: document.getElementById('exportBtn'),
  importBtn: document.getElementById('importBtn'),
  importFile: document.getElementById('importFile'),
  weightInput: document.getElementById('weightInput'),
  logWeightBtn: document.getElementById('logWeightBtn'),
  weightChart: document.getElementById('weightChart'),
  weightLogStatus: document.getElementById('weightLogStatus')
};
